FROM mcr.microsoft.com/vscode/devcontainers/rust
RUN sudo apt update && sudo apt install -y metis lua5.4 liblua5.4-0 liblua5.4-dev pkg-config gperf build-essential bison flex libreadline-dev gawk tcl-dev libffi-dev git graphviz xdot pkg-config python3 libboost-system-dev libboost-python-dev libboost-filesystem-dev zlib1g-dev
#RUN bash build_all.sh
