//! The authority between named signals in the game and ids used by the compiler and APIs.

use once_cell::sync::Lazy;
use std::collections::HashMap;

pub static SIGNAL_MAP: Lazy<(
	HashMap<i32, (&'static str, Option<&'static str>)>,
	HashMap<&'static str, (i32, Option<&'static str>)>,
)> = Lazy::new(|| {
	let mut id = 0;
	let mut m = HashMap::new();
	let mut m2 = HashMap::new();
	let mut signal_type = Some("virtual");
	macro_rules! sig_def {
		($name:expr) => {{
			m.insert(id, ($name, signal_type));
			m2.insert($name, (id, signal_type));
			id += 1;
		}};
	}
	signal_type = None;
	sig_def!("wooden-chest");
	sig_def!("iron-chest");
	sig_def!("steel-chest");
	sig_def!("storage-tank");
	sig_def!("transport-belt");
	sig_def!("fast-transport-belt");
	sig_def!("express-transport-belt");
	sig_def!("underground-belt");
	sig_def!("fast-underground-belt");
	sig_def!("express-underground-belt");
	sig_def!("splitter");
	sig_def!("fast-splitter");
	sig_def!("express-splitter");
	sig_def!("burner-inserter");
	sig_def!("inserter");
	sig_def!("long-handed-inserter");
	sig_def!("fast-inserter");
	sig_def!("bulk-inserter");
	sig_def!("small-electric-pole");
	sig_def!("medium-electric-pole");
	sig_def!("big-electric-pole");
	sig_def!("substation");
	sig_def!("pipe");
	sig_def!("pipe-to-ground");
	sig_def!("pump");
	sig_def!("rail");
	sig_def!("train-stop");
	sig_def!("rail-signal");
	sig_def!("rail-chain-signal");
	sig_def!("locomotive");
	sig_def!("cargo-wagon");
	sig_def!("fluid-wagon");
	sig_def!("artillery-wagon");
	sig_def!("car");
	sig_def!("tank");
	sig_def!("spidertron");
	sig_def!("logistic-robot");
	sig_def!("construction-robot");
	sig_def!("active-provider-chest");
	sig_def!("passive-provider-chest");
	sig_def!("storage-chest");
	sig_def!("buffer-chest");
	sig_def!("requester-chest");
	sig_def!("roboport");
	sig_def!("small-lamp");
	sig_def!("arithmetic-combinator");
	sig_def!("decider-combinator");
	sig_def!("selector-combinator");
	sig_def!("constant-combinator");
	sig_def!("power-switch");
	sig_def!("programmable-speaker");
	sig_def!("display-panel");
	sig_def!("stone-brick");
	sig_def!("concrete");
	sig_def!("hazard-concrete");
	sig_def!("refined-concrete");
	sig_def!("refined-hazard-concrete");
	sig_def!("landfill");
	sig_def!("cliff-explosives");
	sig_def!("repair-pack");
	sig_def!("blueprint");
	sig_def!("deconstruction-planner");
	sig_def!("upgrade-planner");
	sig_def!("blueprint-book");
	sig_def!("boiler");
	sig_def!("steam-engine");
	sig_def!("solar-panel");
	sig_def!("speed-module");
	sig_def!("nuclear-reactor");
	sig_def!("heat-pipe");
	sig_def!("heat-exchanger");
	sig_def!("steam-turbine");
	sig_def!("burner-mining-drill");
	sig_def!("electric-mining-drill");
	sig_def!("offshore-pump");
	sig_def!("pumpjack");
	sig_def!("stone-furnace");
	sig_def!("steel-furnace");
	sig_def!("electric-furnace");
	sig_def!("assembling-machine-1");
	sig_def!("assembling-machine-2");
	sig_def!("assembling-machine-3");
	sig_def!("oil-refinery");
	sig_def!("chemical-plant");
	sig_def!("centrifuge");
	sig_def!("lab");
	sig_def!("beacon");
	sig_def!("accumulator");
	sig_def!("speed-module-2");
	sig_def!("speed-module-3");
	sig_def!("efficiency-module");
	sig_def!("efficiency-module-2");
	sig_def!("efficiency-module-3");
	sig_def!("productivity-module");
	sig_def!("productivity-module-2");
	sig_def!("productivity-module-3");
	sig_def!("rocket-silo");
	sig_def!("cargo-landing-pad");
	sig_def!("satellite");
	sig_def!("wood");
	sig_def!("coal");
	sig_def!("stone");
	sig_def!("iron-ore");
	sig_def!("copper-ore");
	sig_def!("uranium-ore");
	sig_def!("raw-fish");
	sig_def!("iron-plate");
	sig_def!("copper-plate");
	sig_def!("steel-plate");
	sig_def!("solid-fuel");
	sig_def!("plastic-bar");
	sig_def!("sulfur");
	sig_def!("battery");
	sig_def!("explosives");
	sig_def!("water-barrel");
	sig_def!("crude-oil-barrel");
	sig_def!("petroleum-gas-barrel");
	sig_def!("light-oil-barrel");
	sig_def!("heavy-oil-barrel");
	sig_def!("lubricant-barrel");
	sig_def!("sulfuric-acid-barrel");
	sig_def!("water-barrel");
	sig_def!("crude-oil-barrel");
	sig_def!("petroleum-gas-barrel");
	sig_def!("light-oil-barrel");
	sig_def!("heavy-oil-barrel");
	sig_def!("lubricant-barrel");
	sig_def!("sulfuric-acid-barrel");
	sig_def!("iron-gear-wheel");
	sig_def!("iron-stick");
	sig_def!("copper-cable");
	sig_def!("barrel");
	sig_def!("electronic-circuit");
	sig_def!("advanced-circuit");
	sig_def!("processing-unit");
	sig_def!("engine-unit");
	sig_def!("electric-engine-unit");
	sig_def!("flying-robot-frame");
	sig_def!("low-density-structure");
	sig_def!("rocket-fuel");
	sig_def!("rocket-part");
	sig_def!("uranium-235");
	sig_def!("uranium-238");
	sig_def!("uranium-fuel-cell");
	sig_def!("depleted-uranium-fuel-cell");
	sig_def!("nuclear-fuel");
	sig_def!("automation-science-pack");
	sig_def!("logistic-science-pack");
	sig_def!("military-science-pack");
	sig_def!("chemical-science-pack");
	sig_def!("production-science-pack");
	sig_def!("utility-science-pack");
	sig_def!("space-science-pack");
	sig_def!("pistol");
	sig_def!("submachine-gun");
	sig_def!("shotgun");
	sig_def!("combat-shotgun");
	sig_def!("rocket-launcher");
	sig_def!("flamethrower");
	sig_def!("firearm-magazine");
	sig_def!("piercing-rounds-magazine");
	sig_def!("uranium-rounds-magazine");
	sig_def!("shotgun-shell");
	sig_def!("piercing-shotgun-shell");
	sig_def!("cannon-shell");
	sig_def!("explosive-cannon-shell");
	sig_def!("uranium-cannon-shell");
	sig_def!("explosive-uranium-cannon-shell");
	sig_def!("artillery-shell");
	sig_def!("rocket");
	sig_def!("explosive-rocket");
	sig_def!("atomic-bomb");
	sig_def!("flamethrower-ammo");
	sig_def!("grenade");
	sig_def!("cluster-grenade");
	sig_def!("poison-capsule");
	sig_def!("slowdown-capsule");
	sig_def!("defender-capsule");
	sig_def!("distractor-capsule");
	sig_def!("destroyer-capsule");
	sig_def!("light-armor");
	sig_def!("heavy-armor");
	sig_def!("modular-armor");
	sig_def!("power-armor");
	sig_def!("power-armor-mk2");
	sig_def!("solar-panel-equipment");
	sig_def!("fission-reactor-equipment");
	sig_def!("battery-equipment");
	sig_def!("battery-mk2-equipment");
	sig_def!("belt-immunity-equipment");
	sig_def!("exoskeleton-equipment");
	sig_def!("personal-roboport-equipment");
	sig_def!("personal-roboport-mk2-equipment");
	sig_def!("night-vision-equipment");
	sig_def!("energy-shield-equipment");
	sig_def!("energy-shield-mk2-equipment");
	sig_def!("personal-laser-defense-equipment");
	sig_def!("discharge-defense-equipment");
	sig_def!("stone-wall");
	sig_def!("gate");
	sig_def!("radar");
	sig_def!("copper-wire");
	sig_def!("green-wire");
	sig_def!("red-wire");
	sig_def!("spidertron-remote");
	sig_def!("discharge-defense-remote");
	sig_def!("artillery-targeting-remote");

	sig_def!("signal-0");
	sig_def!("signal-1");
	sig_def!("signal-2");
	sig_def!("signal-3");
	sig_def!("signal-4");
	sig_def!("signal-5");
	sig_def!("signal-6");
	sig_def!("signal-7");
	sig_def!("signal-8");
	sig_def!("signal-9");
	sig_def!("signal-A");
	sig_def!("signal-B");
	sig_def!("signal-C");
	sig_def!("signal-D");
	sig_def!("signal-E");
	sig_def!("signal-F");
	sig_def!("signal-G");
	sig_def!("signal-H");
	sig_def!("signal-I");
	sig_def!("signal-J");
	sig_def!("signal-K");
	sig_def!("signal-L");
	sig_def!("signal-M");
	sig_def!("signal-N");
	sig_def!("signal-O");
	sig_def!("signal-P");
	sig_def!("signal-Q");
	sig_def!("signal-R");
	sig_def!("signal-S");
	sig_def!("signal-T");
	sig_def!("signal-U");
	sig_def!("signal-V");
	sig_def!("signal-X");
	sig_def!("signal-Y");
	sig_def!("signal-Z");
	sig_def!("signal-red");
	sig_def!("signal-green");
	sig_def!("signal-blue");
	sig_def!("signal-yellow");
	sig_def!("signal-pink");
	sig_def!("signal-cyan");
	sig_def!("signal-white");
	sig_def!("signal-grey");
	sig_def!("signal-black");
	sig_def!("signal-check");
	sig_def!("signal-deny");
	sig_def!("signal-info");
	sig_def!("signal-dot");
	sig_def!("shape-vertical");
	sig_def!("shape-horizontal");
	sig_def!("shape-diagonal");
	sig_def!("shape-curve");
	sig_def!("shape-cross");
	sig_def!("shape-diagonal-cross");
	sig_def!("shape-corner");
	sig_def!("shape-t");
	sig_def!("shape-circle");
	sig_def!("up-arrow");
	sig_def!("up-right-arrow");
	sig_def!("right-arrow");
	sig_def!("down-right-arrow");
	sig_def!("down-arrow");
	sig_def!("down-left-arrow");
	sig_def!("left-arrow");
	sig_def!("up-left-arrow");
	sig_def!("signal-stack-size");
	sig_def!("signal-heart");
	sig_def!("signal-skull");
	sig_def!("signal-ghost");

	signal_type = Some("recipe");
	sig_def!("basic-oil-processing");
	sig_def!("advanced-oil-processing");
	sig_def!("coal-liquefaction");
	sig_def!("heavy-oil-cracking");
	sig_def!("light-oil-cracking");
	sig_def!("solid-fuel-from-petroleum-gas");
	sig_def!("solid-fuel-from-light-oil");
	sig_def!("solid-fuel-from-heavy-oil");
	sig_def!("nuclear-fuel-reprocessing");
	sig_def!("kovarex-enrichment-process");
	sig_def!("uranium-processing");
	sig_def!("empty-water-barrel");
	sig_def!("empty-crude-oil-barrel");
	sig_def!("empty-petroleum-gas-barrel");
	sig_def!("empty-light-oil-barrel");
	sig_def!("empty-heavy-oil-barrel");
	sig_def!("empty-lubricant-barrel");
	sig_def!("empty-sulfuric-acid-barrel");

	signal_type = Some("fluid");
	sig_def!("water");
	sig_def!("steam");
	sig_def!("crude-oil");
	sig_def!("petroleum-gas");
	sig_def!("light-oil");
	sig_def!("heavy-oil");
	sig_def!("lubricant");
	sig_def!("sulfuric-acid");

	signal_type = Some("space-location");
	sig_def!("nauvis");

	signal_type = Some("entity");
	sig_def!("entity-ghost");
	sig_def!("item-on-ground");
	sig_def!("item-request-proxy");
	sig_def!("tile-ghost");
	sig_def!("land-mine");
	sig_def!("gun-turret");
	sig_def!("laser-turret");
	sig_def!("flamethrower-turret");
	sig_def!("artillery-turret");
	sig_def!("small-biter");
	sig_def!("medium-biter");
	sig_def!("big-biter");
	sig_def!("behemoth-biter");
	sig_def!("small-spitter");
	sig_def!("medium-spitter");
	sig_def!("big-spitter");
	sig_def!("behemoth-spitter");
	sig_def!("small-worm-turret");
	sig_def!("medium-worm-turret");
	sig_def!("big-worm-turret");
	sig_def!("behemoth-worm-turret");
	sig_def!("biter-spawner");
	sig_def!("spitter-spawner");
	sig_def!("cliff");
	sig_def!("character");
	sig_def!("big-sand-rock");
	sig_def!("huge-rock");
	sig_def!("crude-oil");
	sig_def!("defender");
	sig_def!("distractor");
	sig_def!("destroyer");
	(m, m2)
});

pub fn lookup_str(id: i32) -> (&'static str, Option<&'static str>) {
	*SIGNAL_MAP.0.get(&id).unwrap()
}

pub fn lookup_id(mapped_name: &str) -> Option<i32> {
	let id_name = mapped_name.replace("_", "-");
	for (key, value) in &SIGNAL_MAP.1 {
		if id_name.starts_with(*key) {
			return Some(value.0);
		}
	}
	None
}

pub fn lookup_sig(mapped_name: &str) -> crate::logical_design::Signal {
	if let Some(id) = lookup_id(mapped_name) {
		return crate::logical_design::Signal::Id(id);
	}
	panic!("Name doesn't match signal");
}

pub fn n_ids() -> i32 {
	SIGNAL_MAP.0.len() as i32
}
